name: juju-kubectl
base: core18
version: '0.1.0'
summary: Runs kubectl for Kubernetes models in Juju
description: |
  Allows running kubectl easily for Kubernetes models in Juju

grade: devel
confinement: classic

apps:
  juju-kubectl:
    command: juju-kubectl

parts:
  juju-kubectl:
    source: .
    plugin: rust
    # https://forum.snapcraft.io/t/issue-with-rebuilding-a-rust-snap/10830
    override-build: |
      [ -f "$SNAPCRAFT_PART_INSTALL/bin/juju-kubectl" ] && rm "$SNAPCRAFT_PART_INSTALL/bin/juju-kubectl"
      snapcraftctl build

architectures:
  - amd64
  - arm64
  - armhf
  - i386
  - ppc64el
